SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE restaurant_like RESTART IDENTITY;
TRUNCATE TABLE oauth_member RESTART IDENTITY;
TRUNCATE TABLE celeb RESTART IDENTITY;
TRUNCATE TABLE restaurant RESTART IDENTITY;
TRUNCATE TABLE restaurant_image RESTART IDENTITY;
TRUNCATE TABLE restaurant_correction RESTART IDENTITY;
TRUNCATE TABLE video RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
