SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE celeb RESTART IDENTITY;
TRUNCATE TABLE restaurant RESTART IDENTITY;
TRUNCATE TABLE video RESTART IDENTITY;
TRUNCATE TABLE admin RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
